### ISSUE TITLE
Classe PapelMoedaInvaidaException incompleta

### ISSUE THREAD

**Issue by VitoriaPreviato** [VitoriaPreviato/Source-Code-Inspection#1]
Descrição: A classe PapelMoedaInvaidaException não possui implementação alguma.
Classificação: Comissão
Severidade: Baixa

**Comment by LucasPedroLP** [comment]
Issue resolvido. 
Correção feita: foram adicionados dois construtores a classe PapelMoedaInvaidaException, um default  com uma mensagem de erro e um construtor que recebe dois parâmetros - String message e Throwable throwable.
