### ISSUE TITLE
Construtor da classe Troco com lógica desnecessária e algoritmo que não condiz com expectativas

### ISSUE THREAD

**Issue by VitoriaPreviato** [VitoriaPreviato/Source-Code-Inspection#10]
Descrição: Os loops realizados funcionam da maneira errada e são desnecessários, e o método no geral não produz o resultado esperado. O algoritmo poderia ter sido implementado de uma maneira muito mais eficaz e sucinta.
Classificação: Desempenho, Excesso, Dados
Severidade: Alta

**Comment by LucasPedroLP** [comment]
Issue resolvido. 
Correção feita: O código foi totalmente refatorado, removendo os _while_ desnecessários e os substituindo por cálculos simplificados. Além disso a variável _count_ teve seu nome alterado para _quant_notas_ devido as mudanças no código.
