### ISSUE TITLE
Setters dos atributos da classe PapelMoeda não foram implementados

### ISSUE THREAD

**Issue by VitoriaPreviato** [VitoriaPreviato/Source-Code-Inspection#14]
Descrição: Os atributos "valor" e "quantidade" da classe PapelMoeda não possuem seus métodos setters definidos na classe. 
Classificação: Comissão
Severidade: Alta

**Comment by LucasPedroLP** [comment]
Issue resolvido. 
Correção feita: Foram implementados os metodos _setValor_ e _setQuantidade_
