### ISSUE TITLE
Visibilidade dos atributos da classe PapelMoeda não condizem com especificação

### ISSUE THREAD

**Issue by VitoriaPreviato** [VitoriaPreviato/Source-Code-Inspection#15]
Descrição: A visibilidade dos atributos "valor" e "quantidade" da classe PapelMoeda foram definidos como private no documento de requisitos, porém no código eles estão como protected. 
Classificação: Comissão
Severidade: Alta

**Comment by LucasPedroLP** [comment]
Issue resolvido. 
Correção feita: os modificadores de acesso foram atualizados para _private_
