### ISSUE TITLE
Método inserir() da classe TicketMachine com lógica incorreta

### ISSUE THREAD

**Issue by VitoriaPreviato** [VitoriaPreviato/Source-Code-Inspection#18]
Descrição: No método inserir() da classe TicketMachine existe uma estrutura de loop for para encontrar no vetor papelMoeda qual o tipo de cédula inserida. Porém, em vez de comparar cada posição do vetor, a cédula é sempre comparada apenas com a primeira posição do mesmo.
Classificação: Comissão
Severidade: Alta

**Comment by LucasPedroLP** [comment]
Issue resolvido. 
Correção feita: foi trocado o número _1_ fixo entre os colchetes pela variável _i_, que corrigiu o problema comparando o valor a todos os elementos no vetor papelMoeda.
