### ISSUE TITLE
Descrição do projeto ambígua

### ISSUE THREAD

**Issue by LucasPedroLP** [VitoriaPreviato/Source-Code-Inspection#21]
Descrição: Na descrição do projeto, é definido que as máquinas mantêm uma soma total da quantidade de dinheiro que coletou durante toda sua operação, porém não é definido se essa operação é individual ou coletiva.
Classificação: Ambiguidade
Severidade: Baixa

**Comment by VitoriaPreviato** [comment]
Issue resolvido. 
Correção feita: Foi definido no documento de requisitos que a soma total da quantidade de dinheiro que a máquina coletou durante toda sua operação, refere-se ao saldo atual do cliente que está operando a máquina num determinado instante, ou seja, a quantidade de dinheiro que o mesmo inseriu na máquina.
