### ISSUE TITLE
No fluxo de exceção 1 do caso de uso “Inserir dinheiro”, não deveria existir segunda tentativa de leitura da nota inserida

### ISSUE THREAD

**Issue by LucasPedroLP** [VitoriaPreviato/Source-Code-Inspection#26]
Descrição: No fluxo de exceção 1 do caso de uso “Inserir dinheiro”, o passo 4 não deveria retornar ao passo 6 do fluxo principal. Ao invés de dar uma segunda chance para cliente inserir a nota, o processo deveria ser encerrado, voltando ao passo 1 do fluxo principal.
Classificação:  Omissão
Severidade: Média

**Comment by VitoriaPreviato** [comment]
Issue resolvido. 
Correção feita: O passo 4 agora retorna apar o passo 1 do fluxo principal, ao invés do passo 6.
