### ISSUE TITLE
No caso de uso “Solicitar bilhete”, o cliente não tem opção de comprar mais de um bilhete por vez

### ISSUE THREAD

**Issue by LucasPedroLP** [VitoriaPreviato/Source-Code-Inspection#27]
Descrição: O cliente deveria ter opção de comprar mais de um bilhete por vez
Classificação:  Ambiguidade
Severidade: Alta

**Comment by VitoriaPreviato** [comment]
Issue resolvido. 
Correção feita: O sumário, pós-condição e fluxo principal do caso de uso "Solicitar bilhete" foram alterados de modo que o cliente possa escolher uma quantidade de bilhetes antes de imprimi-los.
