### ISSUE TITLE
Classe Troco foi erroneamente definida como uma abstração de TrocoIterator

### ISSUE THREAD

**Issue by LucasPedroLP** [VitoriaPreviato/Source-Code-Inspection#3]
Descrição: A classe Troco não é, nem deveria ser uma abstração de TrocoIterator. O ideal é que cada uma estivesse definida em um arquivo próprio. O erro se encontra na classe "Troco.java". 
Classificação: Comissão. 
Severidade: Média.

**Comment by VitoriaPreviato** [comment]
Issue resolvido.
Correção feita: A classe TrocoIterator foi retirada de dentro da classe Troco, e colocada em um arquivo próprio TrocoIterator.java.
