### ISSUE TITLE
Estrutura de loop for nunca executada no método next() da classe TrocoIterator 

### ISSUE THREAD

**Issue by LucasPedroLP** [VitoriaPreviato/Source-Code-Inspection#4]
Descrição: A variável "ret" no método next() da classe TrocoIterator é definida como null no começo do método, e na linha subsequente é definido um for em que uma das condições de parada é que a variável "ret" seja diferente de null. Portanto este for nunca é executado.
Classificação: Computação
Severidade: Média

**Comment by VitoriaPreviato** [comment]
Issue resolvido. 
Correção feita: A variável ret foi carregada com a primeira posição do ArrayList papeisMoeda no começo do método, e o incremento do for e sua variável i inicial foram alteradas para que todos os elementos do ArrayList sejam verificados pela iteração.
