### ISSUE TITLE
Variável de controle nunca é alterada no construtor da classe Troco, causando loops infinitos

### ISSUE THREAD

**Issue by VitoriaPreviato** [VitoriaPreviato/Source-Code-Inspection#7]
Descrição: A variável de controle "valor" passada no construtor da classe Troco nunca é alterada 
conforme os loops do método são executados, sendo que ela deveria ter seu valor diminuído a cada iteração. Por conta disso, todos os whiles desse método são loops infinitos.
Classificação: Controle
Severidade: Alta

**Comment by LucasPedroLP** [comment]
Issue resolvido. 
Correção feita: foram adicionadas atribuições de valores após a verificação da condição em todos os _while_.
