### ISSUE TITLE
Posição 1 do vetor papeisMoeda no construtor da classe Troco resetado erroneamente 

### ISSUE THREAD

**Issue by VitoriaPreviato** [VitoriaPreviato/Source-Code-Inspection#9]
Descrição: No construtor da classe Troco são definidas as quantidades de cada papel moeda de valor diferente, porém a mesma posição do vetor (no caso a posição 1) é acessada para definir tanto as quantidades de papelMoeda 5 e papelMoeda 2, uma sobrescrevendo a outra. A quantidade de papelMoeda 2 deveria ser inserida na posição 0 do vetor, e como isso nao acontece, a primeira posição do mesmo é null.
Classificação: Computação, Dados
Severidade: Média

**Comment by LucasPedroLP** [comment]
Issue resolvido. 
Correção feita: o índice de _papeisMoeda_ foi alterado na linha 40 de um para zero de forma que a quantidade de notas de cinco não será mais sobrescrita.
